[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter =
  +<main.cpp>
  -<../src_led_test/>
lib_deps =
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
  arduino-irremote/IRremote@^4.4.1

[env:led_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter =
  -<*>
  +<../src_led_test/main.cpp>
