#pragma once

#include <Arduino.h>
#include <avr/pgmspace.h>

// Generated by tools/learn_ir_codes.py.
// Re-run the learner when using another remote.

struct LearnedIrCode {
  uint8_t protocol;
  uint16_t address;
  uint16_t command;
  uint32_t raw;
};

constexpr uint8_t IR_LEARNED_PLAY_COUNT = 1;
const LearnedIrCode IR_LEARNED_PLAY_CODES[] PROGMEM = {
  {7, 0x0040, 0x000A, 0xF50ABF40UL},
};

constexpr uint8_t IR_LEARNED_JUMP_COUNT = 1;
const LearnedIrCode IR_LEARNED_JUMP_CODES[] PROGMEM = {
  {7, 0x0040, 0x0019, 0xE619BF40UL},
};

