#!/usr/bin/env python3
import argparse
import re
import subprocess
import sys
import time
from pathlib import Path

try:
    import serial
except ImportError:
    print("pyserial is required: python3 -m pip install pyserial", file=sys.stderr)
    raise


ROOT = Path(__file__).resolve().parents[1]
HEADER_PATH = ROOT / "include" / "ir_codes.h"

LEARN_RE = re.compile(
    r"LEARN label=(?P<label>\w+)\s+"
    r"protocol=(?P<protocol>\d+)\s+"
    r"address=0x(?P<address>[0-9A-Fa-f]+)\s+"
    r"command=0x(?P<command>[0-9A-Fa-f]+)\s+"
    r"raw=0x(?P<raw>[0-9A-Fa-f]+)\s+"
    r"flags=0x(?P<flags>[0-9A-Fa-f]+)\s+"
    r"repeat=(?P<repeat>yes|no)"
)

HEADER_VALUE_RE = re.compile(
    r"constexpr\s+(?P<type>bool|uint8_t|uint16_t|uint32_t)\s+"
    r"IR_LEARNED_(?P<label>PLAY|JUMP)_(?P<field>ENABLED|PROTOCOL|ADDRESS|COMMAND|RAW)\s*=\s*"
    r"(?P<value>[^;]+);"
)


def run_pio(args):
    subprocess.run(["pio", *args], cwd=ROOT, check=True)


def parse_learn_line(line):
    match = LEARN_RE.search(line)
    if not match:
        return None

    return {
        "label": match.group("label"),
        "protocol": int(match.group("protocol"), 10),
        "address": int(match.group("address"), 16),
        "command": int(match.group("command"), 16),
        "raw": int(match.group("raw"), 16),
        "flags": int(match.group("flags"), 16),
        "repeat": match.group("repeat") == "yes",
    }


def parse_int_literal(value):
    value = value.strip()
    if value.endswith("UL"):
        value = value[:-2]
    if value in {"true", "false"}:
        return value == "true"
    return int(value, 0)


def read_existing_codes():
    if not HEADER_PATH.exists():
        return None

    data = {
        "PLAY": {"label": "PLAY"},
        "JUMP": {"label": "JUMP"},
    }

    for line in HEADER_PATH.read_text(encoding="utf-8").splitlines():
        match = HEADER_VALUE_RE.search(line)
        if not match:
            continue

        label = match.group("label")
        field = match.group("field")
        value = parse_int_literal(match.group("value"))

        if field == "ENABLED":
            data[label]["enabled"] = bool(value)
        elif field == "PROTOCOL":
            data[label]["protocol"] = int(value)
        elif field == "ADDRESS":
            data[label]["address"] = int(value)
        elif field == "COMMAND":
            data[label]["command"] = int(value)
        elif field == "RAW":
            data[label]["raw"] = int(value)

    required = {"protocol", "address", "command", "raw"}
    if not required.issubset(data["PLAY"]) or not required.issubset(data["JUMP"]):
        return None

    return data


def wait_for_learn(ser, label, timeout):
    deadline = time.monotonic() + timeout

    while time.monotonic() < deadline:
        raw_line = ser.readline()
        if not raw_line:
            continue

        line = raw_line.decode("utf-8", "replace").strip()
        if line:
            print(line)

        learned = parse_learn_line(line)
        if learned and learned["label"] == label and not learned["repeat"]:
            return learned

    raise TimeoutError(f"Timed out waiting for {label} IR code")


def capture_button(ser, label, command, timeout):
    print()
    print(f"Press the remote button for {label}.")
    ser.write(command.encode("ascii"))
    ser.flush()
    return wait_for_learn(ser, label, timeout)


def format_header(play, jump):
    return f"""#pragma once

// Generated by tools/learn_ir_codes.py.
// Re-run the learner when using another remote.

constexpr bool IR_LEARNED_PLAY_ENABLED = true;
constexpr uint8_t IR_LEARNED_PLAY_PROTOCOL = {play["protocol"]};
constexpr uint16_t IR_LEARNED_PLAY_ADDRESS = 0x{play["address"]:04X};
constexpr uint16_t IR_LEARNED_PLAY_COMMAND = 0x{play["command"]:04X};
constexpr uint32_t IR_LEARNED_PLAY_RAW = 0x{play["raw"]:08X}UL;

constexpr bool IR_LEARNED_JUMP_ENABLED = true;
constexpr uint8_t IR_LEARNED_JUMP_PROTOCOL = {jump["protocol"]};
constexpr uint16_t IR_LEARNED_JUMP_ADDRESS = 0x{jump["address"]:04X};
constexpr uint16_t IR_LEARNED_JUMP_COMMAND = 0x{jump["command"]:04X};
constexpr uint32_t IR_LEARNED_JUMP_RAW = 0x{jump["raw"]:08X}UL;
"""


def write_header(play, jump):
    HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    HEADER_PATH.write_text(format_header(play, jump), encoding="utf-8")
    print()
    print(f"Wrote {HEADER_PATH}")
    print(f"PLAY protocol={play['protocol']} address=0x{play['address']:X} command=0x{play['command']:X} raw=0x{play['raw']:X}")
    print(f"JUMP protocol={jump['protocol']} address=0x{jump['address']:X} command=0x{jump['command']:X} raw=0x{jump['raw']:X}")


def main():
    parser = argparse.ArgumentParser(description="Learn PLAY and JUMP IR codes over Serial and generate include/ir_codes.h.")
    parser.add_argument("--port", default="/dev/cu.usbserial-110", help="Serial port for Arduino")
    parser.add_argument("--baud", type=int, default=9600, help="Serial baud rate")
    parser.add_argument("--timeout", type=float, default=30.0, help="Seconds to wait for each button")
    parser.add_argument("--upload-test", action="store_true", help="Upload ir_lcd_test before learning")
    parser.add_argument("--build-game", action="store_true", help="Build the main game after writing codes")
    parser.add_argument("--upload-game", action="store_true", help="Upload the main game after writing codes")
    parser.add_argument("--play-only", action="store_true", help="Only relearn PLAY and keep the existing JUMP code")
    parser.add_argument("--jump-only", action="store_true", help="Only relearn JUMP and keep the existing PLAY code")
    args = parser.parse_args()

    if args.play_only and args.jump_only:
        parser.error("--play-only and --jump-only are mutually exclusive")

    existing = read_existing_codes()
    if (args.play_only or args.jump_only) and existing is None:
        parser.error("include/ir_codes.h does not contain existing codes to preserve")

    if args.upload_test:
        run_pio(["run", "-e", "ir_lcd_test", "-t", "upload", "--upload-port", args.port])
        time.sleep(1.5)

    with serial.Serial(args.port, args.baud, timeout=0.25) as ser:
        time.sleep(2.0)
        ser.reset_input_buffer()
        ser.write(b"I")
        ser.flush()

        if args.jump_only:
            play = existing["PLAY"]
        else:
            play = capture_button(ser, "PLAY", "P", args.timeout)

        if args.play_only:
            jump = existing["JUMP"]
        else:
            jump = capture_button(ser, "JUMP", "J", args.timeout)

    write_header(play, jump)

    if args.build_game or args.upload_game:
        run_pio(["run", "-e", "uno"])

    if args.upload_game:
        run_pio(["run", "-e", "uno", "-t", "upload", "--upload-port", args.port])


if __name__ == "__main__":
    main()
